### ISSUE TITLE
História 


### ISSUE THREAD

**Issue by setimos** [Matt-Fontes/SendScriptWhatsApp#18]

**Comment by PennyworthAlfred** [comment]
FUNCIONA SUPER BEM, porém teria como locar em loop? Se sim, como?

**Comment by marchiartur** [comment]
para você adicionar um loop basta colocar um laço condicional, segue abaixo o exemplo:

`
async function enviarScript(scriptText){
    const lines = scriptText.split(/[\n\t]+/).map(line => line.trim()).filter(line => line),
	main = document.querySelector("#main"),
	textarea = main.querySelector(`div[contenteditable="true"]`)

	if(!textarea) throw new Error("Não há uma conversa aberta")

	for(const line of lines){
		console.log(line)

		textarea.textContent = line
		textarea.dispatchEvent(new InputEvent("input", { bubbles: true }));

		(main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click()
		
		if(lines.indexOf(line) !== lines.length - 1) await new Promise(resolve => setTimeout(resolve, 250))
	}

	return lines.length
}

let quantity = 50;

for (let i = 0; i < 50; i++) {
 enviarScript('here you put the text').then(e => console.log(`Código finalizado, ${e} mensagens enviadas`)).catch(console.error)
}
`

apenas troque `here you put the text` pelo roteiro do filme

**Comment by marchiartur** [comment]
Close #18

**Comment by marchiartur** [comment]
@Matt-Fontes, @WillFelisberto, @P0sseid0n could you close this issue? https://github.com/Matt-Fontes/SendScriptWhatsApp/issues/18
