### ISSUE TITLE
Erro ao enviar

### ISSUE THREAD

**Issue by Bulani** [Matt-Fontes/SendScriptWhatsApp#30]
Não esta funcionando o envio:

TypeError: Cannot read properties of null (reading 'click')
    at enviarScript (<anonymous>:14:92)

![Screenshot_1](https://user-images.githubusercontent.com/13426175/180056821-be28c101-0144-4c0e-bd06-d154df8cf12e.png)

**Comment by VICTORHUGOBRZ** [comment]
Aqui também não funciona mais. Alguém consegue uma solução? 
Here it also doesn't work anymore. Does anyone get a solution?

**Comment by marchiartur** [comment]
Acredito que vocês (@VICTORHUGOBRZ  e @Bulani) tenham executado algum passo de maneira errada, pois acabo de testar, e está funcionando.

1. Copie o texto cru do link: "https://github.com/Matt-Fontes/SendScriptWhatsApp/blob/main/shrekSendScript.js"
2. Abra uma conversa no WhatsApp
3. Abra o console do navegador com f12
4. Cole o texto copiado
5. Pressione Enter para executar

**Comment by Bulani** [comment]
@marchiartur Antes não estava funcionando, foi corrigido

**Comment by marchiartur** [comment]
@Bulani creio que convém fechar a "issue"
