### ISSUE TITLE
Parou de funcionar! / It`s not working anymore

### ISSUE THREAD

**Issue by VICTORHUGOBRZ** [Matt-Fontes/SendScriptWhatsApp#32]
Não está funcionando mais!

Ao colar o código, aparece esse erro abaixo

TypeError: Cannot read properties of null (reading 'click')
  
<img width="443" alt="Captura de Tela 2022-07-27 às 19 44 14" src="https://user-images.githubusercontent.com/110135507/181385206-b4c2c28f-397a-4244-aeab-661828144a98.png">

**Comment by VICTORHUGOBRZ** [comment]
TypeError: Cannot read properties of null (reading 'click')
    at enviarScript (<anonymous>:14:92)
    at <anonymous>:22:1

**Comment by guustavoveloso** [comment]
Try to change the function for this one:

`async function enviarScript(scriptText){
    const lines = scriptText.split(/[\n\t]+/).map(line => line.trim()).filter(line => line),
	main = document.querySelector("#main"),
	textarea = main.querySelector(`div[contenteditable="true"]`)

	if(!textarea) throw new Error("Não há uma conversa aberta")

	for(const line of lines){
		console.log(line)

		textarea.focus();
        document.execCommand('insertText', false, line);
        textarea.dispatchEvent(new Event('change', {bubbles: true}));

        setTimeout(() => {
            (main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click();
        }, 100);
		
		if(lines.indexOf(line) !== lines.length - 1) await new Promise(resolve => setTimeout(resolve, 250));
	}

	return lines.length;
}`

**Comment by VICTORHUGOBRZ** [comment]
@guustavoveloso consegue me mandar o código atualizado por favor? Fiz a troca aqui, mas não deu certo

**Comment by LexFalconis** [comment]
> Try to change the function for this one:
> 
> `
> 
> async function enviarScript(scriptText){
> 
> ```
> const lines = scriptText.split(/[\n\t]+/).map(line => line.trim()).filter(line => line);
> main = document.querySelector("#main"),
> textarea = main.querySelector(`div[contenteditable="true"]`)
> 
> if(!textarea) throw new Error("Não há uma conversa aberta")
> 
> for(const line of lines){
> 	console.log(line)
> 
> 	textarea.focus();
>     document.execCommand('insertText', false, line);
>     textarea.dispatchEvent(new Event('change', {bubbles: true}));
> 
>     setTimeout(() => {
>         (main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click();
>     }, 100);
> 	
> 	if(lines.indexOf(line) !== lines.length - 1) await new Promise(resolve => setTimeout(resolve, 250));
> }
> 
> return lines.length;
> ```
> 
> } `

Po Gustavo, vlw hein, não manjo JS e já estava doido por falta de solução hahahaha.
Tô quase fazendo fork do projeto e colocando sua solução p meu uso... Tudo bem se eu fizer isso? Claro que colocaria os devidos créditos no Readme.

**Comment by VICTORHUGOBRZ** [comment]
@LexFalconis o código foi atualizado na página principal?

**Comment by LexFalconis** [comment]
> @LexFalconis teste aqui e não funcionou!

o código do @guustavoveloso funcionou p mim hj, já estava louco sem conseguir usar hahahaha
Dá uma olhada se não foi o local onde colocou o código dele. Segue print do que fiz com o código dele... Finaliza com o que já estava que era o texto do filme Shrek

![image](https://user-images.githubusercontent.com/11050446/183528492-8e714020-e353-4300-b17c-4053c68e9ee0.png)

**Comment by jamn2n** [comment]
@guustavoveloso Obrigado! Salvou muito deu certinho!

**Comment by VICTORHUGOBRZ** [comment]
@LexFalconis obrigado pela captura de tela, consegui aqui. To spammando geral com um WhatsApp fake KKKKKK 

Se puder, atualiza lá o código pra galera conseguir usar

**Comment by LexFalconis** [comment]
> @LexFalconis obrigado pela captura de tela, consegui aqui. Percebi que agora as 3 mil mensagens estão sendo enviadas mais rápidas. To spammando geral com um WhatsApp fake KKKKKK
> 
> Se puder, atualiza lá o código pra galera conseguir usar

não fiz pull request pq a solução que apliquei não foi minha, foi a do @guustavoveloso, eu só mandei print pq vc comentou que não conseguiu
